sudo: false

addons:
  apt:
    packages:
    - libjpeg-turbo8
    - libjpeg-turbo8-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - liblcms2-2
    - liblcms2-dev
    - liblcms-utils
    - libtiff4-dev
    - libwebp-dev

language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=2.7

  allow_failures:
    - python: 3.4
      env: TOXENV=3.4
    - python: 3.5
      env: TOXENV=3.5
    - python: 3.6
      env: TOXENV=3.6

install:
  - pip install --upgrade pip setuptools
  - pip install --upgrade tox

script:
  - tox

notifications:
  email:
    recipients: "jpstroop@gmail.com"
    on_success: "always"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
